[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"


[project]
name = "naptrap_pipeline"
description = "Package to analyze nap-trap data."
version = "0.0.1"
authors = [{name = "Ethan C Strayer", email = "ethancstrayer@gmail.com"},
            {name = "Srihari Madhavan", email = "smadhavan@uchc.edu"}]
requires-python = ">=3.9"
dependencies = ["matplotlib<3.10",
                "seaborn<0.14",
                "numpy<2.2",
                "pandas<2.3",
                "pyfaidx<0.9",
                "matplotlib-venn<1.2",
                "toml<0.11",
                "scipy<1.15"]
license = "MPL-2.0" 
license-files = ['LICENSE']
readme = "README.MD"


[tool.setuptools.packages.find]
where = ["src"] 

[tool.setuptools_scm]

[project.scripts]
naptrap_count_reads = "naptrap_scripts.count_reads:main"
naptrap_count_unique = "naptrap_scripts.count_unique:main"
naptrap_build_db = "naptrap_scripts.build_db:main"
naptrap_read_cutoff_decision = "naptrap_scripts.read_cutoff_decision:main"
naptrap = "naptrap_scripts.naptrap_wrapper:main"


[project.urls]
homepage = "https://github.com/SrihariMadhavan/nap-trap_paper"